baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'testing equations in quarto `hugo-md` export'
theme = 'ananke'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
[params]
  math = true
